version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker
    restart: unless-stopped
    environment:
      - PORT=4000
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=development
      - CRYPT_SALT=10
      - JWT_SECRET_KEY=secret123123
      - JWT_SECRET_REFRESH_KEY=secret123123
      - TOKEN_EXPIRE_TIME=1h
      - TOKEN_REFRESH_EXPIRE_TIME=24h

    ports:
      - '4000:4000'
    depends_on:
      - postgres


  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=db
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data

networks:
  default:
    driver: bridge
    external: true

volumes:
  pgdata: {}


