# Use the official PostgreSQL image from Docker Hub
FROM postgres:latest

# Set environment variables
ENV POSTGRES_USER=user
ENV POSTGRES_PASSWORD=password
ENV POSTGRES_DB=db

# Expose PostgreSQL port
EXPOSE 5432

# Start PostgreSQL service
CMD ["postgres"]



# FROM postgres:latest

# ENV POSTGRES_DB=${POSTGRES_DB}
# ENV POSTGRES_USER=${POSTGRES_USER}
# ENV POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# VOLUME /var/lib/postgresql@16/data

# EXPOSE 5432

# CMD ["postgres"]
