version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker
    restart: always
    environment:
      - PORT=${PORT}
      # - DATABASE_URL=postgres://user:password@postgress:5432/db
      - NODE_ENV=development
      - CRYPT_SALT=10
      - JWT_SECRET_KEY=secret123123
      - JWT_SECRET_REFRESH_KEY=secret123123
      - TOKEN_EXPIRE_TIME=1h
      - TOKEN_REFRESH_EXPIRE_TIME=24h

    ports:
      - '4000:4000'
    depends_on:
      - postgres

  postgres:
    build: ./postgres
    image: postgres:10.4
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data

networks:
  default:
    driver: bridge


